"""empty message

Revision ID: 8c005835f5ba
Revises: d2318b231ec5
Create Date: 2019-10-26 01:48:11.517993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c005835f5ba'
down_revision = 'd2318b231ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('classroom_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'classroom_num')
    # ### end Alembic commands ###
